sudo: false
language: node_js
node_js: "11"

addons:
  sonarcloud:
    organization: "sonarcloud"

script:
  - npm test

after_script:
  - npm run tslint
  - ls -l
  - npm install nyc
  - nyc --reporter=lcov --reporter=text-lcov npm test
  - bash <(curl -s https://codecov.io/bash)
  - sonar-scanner
